# Nome da Actions:  
2
name: Snake Game
3
​
4
# Controlador do tempo que sera feito a atualização dos arquivos.
5
on:
6
  schedule:
7
      # Será atualizado a cada 5 horas.
8
    - cron: "0 */5 * * *"
9
​
10
# Permite executar na na lista de Actions (utilizado para testes de build).
11
  workflow_dispatch:
12
​
13
# Regras
14
jobs:
15
  build:
16
    runs-on: ubuntu-latest
17
    steps:
18
​
19
    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
20
      - uses: actions/checkout@v2
21
​
22
    # Repositorio que será utilizado para gerar os arquivos.
23
      - uses: Platane/snk@master
24
        id: snake-gif
25
        with:
26
          github_user_name: brokadev #Seu usuario
27
          gif_out_path: dist/github-contribution-grid-snake.gif
28
          svg_out_path: dist/github-contribution-grid-snake.svg
29
​
30
      - run: git status
